import { useEffect, useMemo, useState } from "react";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import { ArrowUpRight, Check, ChevronRight, CircleDot, ClipboardCheck, CloudCog, FileText, Fingerprint, GitBranch, Landmark, LockKeyhole, Menu, Network, Plus, ShieldCheck, Sparkles, X } from "lucide-react";

const demoSteps = [
  { label: "Application submitted", dept: "SetuGov", status: "complete", date: "04 Sep" },
  { label: "Identity & revenue verified", dept: "Revenue Department", status: "complete", date: "05 Sep" },
  { label: "Address verification", dept: "Local Administration", status: "active", date: "In progress" },
  { label: "Registry approval", dept: "Business Registry", status: "next", date: "Next" },
];
const demoApps = [{ id: "SG-2026-00001", name: "Northstar Foods", type: "Private Limited", status: "In review", updated: "Today, 10:42" }, { id: "SG-2026-00014", name: "Aarav Design Studio", type: "Sole proprietorship", status: "Action required", updated: "Yesterday" }];

function StatusBadge({ status }: { status: string }) { const tone = status.toLowerCase().includes("action") ? "warning" : status.toLowerCase().includes("approved") ? "success" : "info"; return <Badge className={`status-${tone}`}>{status}</Badge>; }

export default function Home() {
  const { user, loading } = useAuth();
  const [mobileOpen, setMobileOpen] = useState(false);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [form, setForm] = useState({ businessName: "", businessType: "Private Limited", address: "", contact: "", documentRef: "" });
  const bootstrap = trpc.platform.bootstrap.useQuery(undefined, { staleTime: Infinity });
  const stats = trpc.platform.stats.useQuery(undefined, { staleTime: 30000 });
  const services = trpc.platform.services.useQuery(undefined, { staleTime: Infinity });
  const apps = trpc.platform.applications.useQuery(undefined, { enabled: Boolean(user), staleTime: 30000 });
  const demoDetail = trpc.platform.demoDetail.useQuery(undefined, { staleTime: 30000 });
  const adminOverview = trpc.platform.adminOverview.useQuery(undefined, { enabled: user?.role === "admin", staleTime: 30000 });
  const officialQueue = trpc.platform.officialQueue.useQuery(undefined, { enabled: user?.role === "official" || user?.role === "admin", staleTime: 30000 });
  const updateStep = trpc.platform.updateStep.useMutation({ onSuccess: () => { toast.success("Milestone updated"); officialQueue.refetch(); demoDetail.refetch(); } });
  const create = trpc.platform.createApplication.useMutation({ onSuccess: (result) => { toast.success(`${result.applicationNumber} submitted`); setDialogOpen(false); apps.refetch(); }, onError: () => toast.error("Please sign in to submit an application") });
  useEffect(() => { if (bootstrap.error) toast.error("Demo data could not be loaded"); }, [bootstrap.error]);
  const greeting = user?.name?.split(" ")[0] || "there";
  const role = user?.role === "admin" ? "Platform administrator" : user?.role === "official" ? "Department official" : "Citizen & business portal";
  const applicationRows = apps.data?.length ? apps.data.map(a => ({ id: a.applicationNumber, name: a.businessName, type: a.businessType, status: a.status.replace("_", " "), updated: new Date(a.updatedAt).toLocaleDateString() })) : demoApps;
  const liveStats = stats.data || { active: 18, pending: 7, approved: 42, avgDays: 3.2 };
  const timelineSteps = demoDetail.data?.steps?.map(step => ({ label: step.label, dept: step.responsibleRole, status: step.status === "completed" ? "complete" : step.status === "in_progress" ? "active" : "next", date: step.completedAt ? new Date(step.completedAt).toLocaleDateString(undefined, { day: "2-digit", month: "short" }) : step.status === "in_progress" ? "In progress" : "Next" })) || demoSteps;
  const submitApplication = () => { if (!user) { startLogin(); return; } create.mutate({ ...form, consentScopes: ["identity", "business profile", "registered address"], documents: form.documentRef ? [{ type: "Supporting document", fileName: "supporting-document-reference", referenceUrl: form.documentRef }] : [] }); };
  const featuredService = services.data?.[0];
  return <div className="app-shell">
    <aside className={`sidebar ${mobileOpen ? "open" : ""}`}>
      <div className="brand"><div className="brand-mark"><Network size={19} /></div><div><strong>SetuGov</strong><span>Interoperability layer</span></div></div>
      <div className="workspace-label">WORKSPACE</div>
      <nav><a className="nav-item active"><span className="nav-icon"><Landmark size={17} /></span>Overview</a><a href="/operations" className="nav-item"><span className="nav-icon"><ClipboardCheck size={17} /></span>Applications <span className="nav-count">{liveStats.active}</span></a><a href="/consent" className="nav-item"><span className="nav-icon"><ShieldCheck size={17} /></span>Consent & sharing</a><a href="/official" className="nav-item"><span className="nav-icon"><GitBranch size={17} /></span>Interoperability</a><a href="/admin" className="nav-item"><span className="nav-icon"><FileText size={17} /></span>Activity log</a></nav>
      <div className="sidebar-bottom"><div className="privacy-card"><LockKeyhole size={16} /><div><b>Privacy by purpose</b><span>Only the data each department needs.</span></div></div><div className="user-chip"><div className="avatar">{user?.name?.[0] || "A"}</div><div className="user-meta"><b>{user?.name || "Demo workspace"}</b><span>{role}</span></div><ChevronRight size={15} className="muted" /></div></div>
    </aside>
    <main className="main-content">
      <header className="topbar"><button className="mobile-menu" onClick={() => setMobileOpen(v => !v)}><Menu size={20} /></button><div className="breadcrumbs"><span>Workspace</span><ChevronRight size={14} /><b>Overview</b></div><div className="top-actions"><div className="secure-indicator"><span className="pulse" />All systems operational</div>{user ? <Button variant="outline" size="sm" onClick={() => window.location.reload()}>Refresh</Button> : <Button size="sm" onClick={startLogin}>Sign in</Button>}</div></header>
      <div className="content-wrap">
        <section className="hero-row"><div><div className="eyebrow"><Sparkles size={13} />CONNECTED SERVICE DELIVERY</div><h1>Good morning, {greeting}.</h1><p className="hero-copy">One application. The right departments. A clearer journey from request to resolution.</p></div><Dialog open={dialogOpen} onOpenChange={setDialogOpen}><DialogTrigger asChild><Button className="primary-cta"><Plus size={17} /> Start an application <ArrowUpRight size={16} /></Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Start business registration</DialogTitle></DialogHeader><div className="dialog-form"><label>Business name<Input placeholder="e.g. Northstar Foods" value={form.businessName} onChange={e => setForm({ ...form, businessName: e.target.value })} /></label><label>Business type<Input value={form.businessType} onChange={e => setForm({ ...form, businessType: e.target.value })} /></label><label>Registered address<Textarea placeholder="Full address" value={form.address} onChange={e => setForm({ ...form, address: e.target.value })} /></label><label>Contact email<Input placeholder="you@business.com" value={form.contact} onChange={e => setForm({ ...form, contact: e.target.value })} /></label><label>Document reference<Input placeholder="https://… or department://…" value={form.documentRef} onChange={e => setForm({ ...form, documentRef: e.target.value })} /></label><div className="consent-note"><ShieldCheck size={16} /><span>By continuing, you allow Revenue, Local Administration and Business Registry to use only the selected information for registration verification.</span></div><Button onClick={submitApplication} disabled={create.isPending} className="w-full">{create.isPending ? "Submitting…" : "Review & submit"}</Button></div></DialogContent></Dialog></section>
        <section className="metric-grid"><Card className="metric-card accent"><CardContent><div className="metric-top"><span>Active applications</span><ClipboardCheck size={17} /></div><strong>{liveStats.active}</strong><small><span className="trend-up">+12%</span> from last month</small></CardContent></Card><Card className="metric-card"><CardContent><div className="metric-top"><span>Awaiting your action</span><CircleDot size={17} /></div><strong>{liveStats.pending}</strong><small>Across connected services</small></CardContent></Card><Card className="metric-card"><CardContent><div className="metric-top"><span>Average turnaround</span><CloudCog size={17} /></div><strong>{liveStats.avgDays}<em> days</em></strong><small><span className="trend-up">1.4 days faster</span> this quarter</small></CardContent></Card><Card className="metric-card soft"><CardContent><div className="metric-top"><span>Records coordinated</span><Fingerprint size={17} /></div><strong>{liveStats.approved + 128}</strong><small>With purpose-limited access</small></CardContent></Card></section>
        <section className="dashboard-grid"><Card className="tracking-card"><CardHeader><div><div className="card-kicker">LIVE APPLICATION</div><CardTitle>Northstar Foods</CardTitle><span className="application-id">SG-2026-00001 <span>·</span> Business registration</span></div><StatusBadge status="In review" /></CardHeader><CardContent><div className="timeline">{timelineSteps.map((step, i) => <div className={`timeline-step ${step.status}`} key={step.label}><div className="timeline-line" /><div className="timeline-dot">{step.status === "complete" ? <Check size={13} /> : step.status === "active" ? <span /> : <CircleDot size={12} />}</div><div className="step-copy"><b>{step.label}</b><span>{step.dept}</span></div><time>{step.date}</time></div>)}</div><div className="tracking-footer"><div><ShieldCheck size={15} /><span>Data shared with <b>2 of 3</b> departments</span></div><Button variant="ghost" size="sm" onClick={() => window.location.assign("/operations")}>View full timeline <ArrowUpRight size={14} /></Button></div></CardContent></Card><Card className="service-card"><CardHeader><div className="card-kicker">AVAILABLE SERVICE</div><CardTitle>Business registration</CardTitle></CardHeader><CardContent><p>Register your business once and let connected departments verify the details securely.</p><div className="service-meta"><span><Landmark size={14} />3 departments</span><span><CloudCog size={14} />~7 days</span></div><div className="department-stack"><span>RE</span><span>LA</span><span>BR</span><small>Revenue · Local Admin · Registry</small></div><Button className="service-button" onClick={() => setDialogOpen(true)}>View service details <ChevronRight size={15} /></Button></CardContent></Card></section>
        <section className="lower-grid"><Card className="apps-card"><CardHeader><div><div className="card-kicker">YOUR WORKSPACE</div><CardTitle>Recent applications</CardTitle></div><Button variant="ghost" size="sm">View all <ArrowUpRight size={14} /></Button></CardHeader><CardContent><div className="app-table"><div className="table-head"><span>APPLICATION</span><span>STATUS</span><span>UPDATED</span></div>{applicationRows.map(app => <div className="table-row" key={app.id}><div className="app-name"><div className="app-symbol"><FileText size={15} /></div><div><b>{app.name}</b><span>{app.id} · {app.type}</span></div></div><StatusBadge status={app.status} /><time>{app.updated}</time><ChevronRight size={15} className="muted" /></div>)}</div></CardContent></Card><Card className="interop-card"><CardHeader><div><div className="card-kicker">FEDERATED NETWORK</div><CardTitle>Interoperability health</CardTitle></div><Badge className="status-success">Healthy</Badge></CardHeader><CardContent><div className="network-score"><strong>98.4%</strong><span>successful exchanges</span><div className="score-bar"><i /></div></div><div className="connector-row"><span className="connector-status healthy" /><div><b>Revenue e-Verify</b><small>Legacy REST · 99% success rate</small></div><span className="connector-latency">142ms</span></div><div className="connector-row"><span className="connector-status healthy" /><div><b>Municipal Property Ledger</b><small>SOAP bridge · 97% success rate</small></div><span className="connector-latency">218ms</span></div><div className="connector-row"><span className="connector-status degraded" /><div><b>National Business Register</b><small>JSON API · 94% success rate</small></div><span className="connector-latency">306ms</span></div><div className="network-note"><Network size={15} /> Source records stay with their departments. SetuGov only coordinates the exchange.</div></CardContent></Card></section>
        {(user?.role === "official" || user?.role === "admin") && <section className="role-panel"><div className="role-panel-copy"><div className="card-kicker">DEPARTMENT WORK QUEUE</div><h2>Cases assigned to your department</h2><p>{officialQueue.data?.length || 0} case(s) visible through server-side role and department boundaries.</p></div><div className="queue-items">{officialQueue.data?.slice(0, 2).map(item => <div className="queue-item" key={item.id}><span><b>{item.applicationNumber}</b><small>{item.businessName} · {item.status.replace("_", " ")}</small></span><Button size="sm" onClick={() => toast.info("Open the case timeline to review its protected fields")}>Review</Button></div>)}</div></section>}
        {user?.role === "admin" && <section className="role-panel admin-panel"><div className="role-panel-copy"><div className="card-kicker">PLATFORM CONTROL PLANE</div><h2>Administration & governance</h2><p>{adminOverview.data ? `${adminOverview.data.departments.length} departments · ${adminOverview.data.connectors.length} connectors · ${adminOverview.data.audits.length} immutable audit entries` : "Loading protected governance data…"}</p></div><div className="admin-live-list">{adminOverview.data?.connectors.slice(0, 3).map(connector => <span key={connector.id}><i className={`connector-status ${connector.status === "healthy" ? "healthy" : "degraded"}`} />{connector.name}<small>{connector.successRate}%</small></span>)}</div></section>}
        <section className="footer-note"><ShieldCheck size={15} /><span>Your data is encrypted in transit and shared only after purpose-limited consent.</span><a>Read our data-sharing principles <ArrowUpRight size={13} /></a></section>
      </div>
    </main>
  </div>;
}
