import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { adminProcedure, protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { and, desc, eq } from "drizzle-orm";
import { applications, auditLogs, connectors, departments, documents, consents, integrationEvents, services, serviceDepartments, workflowSteps, getDb, seedDemoData, listApplications, applicationDetail, demoApplicationDetail, dashboardStats, writeAudit } from "./db";

const officialProcedure = protectedProcedure.use(({ ctx, next }) => {
  if (!ctx.user || (ctx.user.role !== "official" && ctx.user.role !== "admin")) throw new TRPCError({ code: "FORBIDDEN", message: "Official access required" });
  return next({ ctx });
});

export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(opts => opts.ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => { ctx.res.clearCookie(COOKIE_NAME, { ...getSessionCookieOptions(ctx.req), maxAge: -1 }); return { success: true } as const; }),
  }),
  platform: router({
    bootstrap: publicProcedure.query(async () => { await seedDemoData(); return { ready: true }; }),
    stats: publicProcedure.query(() => dashboardStats()),
    services: publicProcedure.query(async () => { await seedDemoData(); const db = await getDb(); return db ? db.select().from(services).where(eq(services.status, "available")) : []; }),
    departments: publicProcedure.query(async () => { await seedDemoData(); const db = await getDb(); return db ? db.select().from(departments) : []; }),
    applications: protectedProcedure.query(async ({ ctx }) => { await seedDemoData(); return listApplications(ctx.user.id, ctx.user.role, ctx.user.departmentId ?? undefined); }),
    demoDetail: publicProcedure.query(async () => { await seedDemoData(); return demoApplicationDetail(); }),
    detail: protectedProcedure.input(z.object({ id: z.number() })).query(async ({ ctx, input }) => { const result = await applicationDetail(input.id); if (!result) return null; if (ctx.user.role === "user" && result.application.applicantId !== ctx.user.id) throw new Error("Application access denied"); return result; }),
    createApplication: protectedProcedure.input(z.object({ businessName: z.string().min(2), businessType: z.string().min(2), address: z.string().min(8), contact: z.string().min(3), consentScopes: z.array(z.string()).min(1), documents: z.array(z.object({ type: z.string(), fileName: z.string(), referenceUrl: z.string().optional() })).default([]) })).mutation(async ({ ctx, input }) => { await seedDemoData(); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const [service] = await db.select().from(services).where(eq(services.slug, "business-registration")); const route = await db.select({ departmentId: serviceDepartments.departmentId, sequence: serviceDepartments.sequence }).from(serviceDepartments).where(eq(serviceDepartments.serviceId, service.id)).orderBy(serviceDepartments.sequence); const count = await db.select({ id: applications.id }).from(applications); const number = `SG-${new Date().getFullYear()}-${String(count.length + 1).padStart(5, "0")}`; const [created] = await db.insert(applications).values({ applicationNumber: number, applicantId: ctx.user.id, serviceId: service.id, businessName: input.businessName, businessType: input.businessType, address: input.address, contact: input.contact, status: "submitted", currentDepartmentId: route[0].departmentId, submittedAt: new Date() }).$returningId(); await db.insert(workflowSteps).values(route.map((r, i) => ({ applicationId: created.id, departmentId: r.departmentId, stepKey: ["identity", "address", "approval"][i] || `step-${i + 1}`, label: ["Identity verification", "Address verification", "Registry approval"][i] || `Verification ${i + 1}`, sequence: r.sequence, status: i === 0 ? ("in_progress" as const) : ("pending" as const), responsibleRole: "Department official", startedAt: i === 0 ? new Date() : null }))); await db.insert(documents).values(input.documents.map(d => ({ applicationId: created.id, documentType: d.type, fileName: d.fileName, referenceUrl: d.referenceUrl, status: "referenced" as const }))); await db.insert(consents).values({ applicationId: created.id, applicantId: ctx.user.id, purpose: "Business registration verification", dataScopes: JSON.stringify(input.consentScopes), status: "granted" }); await db.insert(integrationEvents).values({ applicationId: created.id, direction: "outbound", eventType: "application.submitted", sourceSchema: "citizen.businessRegistration.v1", canonicalSchema: "setugov.application.v1", payloadSummary: "Validated, consent-gated, normalized, and routed to the first department", status: "processed" }); await writeAudit(ctx.user.id, ctx.user.role, "application.submitted", "application", number, "Purpose-limited consent and document references recorded"); return { id: created.id, applicationNumber: number }; }),
    officialQueue: officialProcedure.query(async ({ ctx }) => { await seedDemoData(); return listApplications(ctx.user.id, ctx.user.role, ctx.user.departmentId ?? undefined); }),
    updateConsent: protectedProcedure.input(z.object({ applicationId: z.number(), status: z.enum(["granted", "revoked"]) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const [app] = await db.select().from(applications).where(and(eq(applications.id, input.applicationId), eq(applications.applicantId, ctx.user.id))); if (!app) throw new Error("Application access denied"); await db.update(consents).set({ status: input.status, revokedAt: input.status === "revoked" ? new Date() : null }).where(eq(consents.applicationId, input.applicationId)); await writeAudit(ctx.user.id, ctx.user.role, `consent.${input.status}`, "consent", String(input.applicationId)); return { success: true }; }),
    connectorExchange: officialProcedure.input(z.object({ applicationId: z.number(), connectorId: z.number(), source: z.enum(["revenue", "municipal"]), payload: z.record(z.string(), z.string()) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const port = process.env.PORT || "3000"; const response = await fetch(`http://127.0.0.1:${port}/api/connectors/${input.source}/${input.source === "revenue" ? "verify" : "address"}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(input.payload) }); const exchange = await response.json() as { canonical?: Record<string, unknown> }; const normalized = exchange.canonical || (input.source === "revenue" ? { name: input.payload.citizen_name, dateOfBirth: input.payload.dob } : { name: input.payload.fullName, dateOfBirth: input.payload.date_of_birth?.split("/").reverse().join("-") }); await db.insert(integrationEvents).values({ applicationId: input.applicationId, connectorId: input.connectorId, direction: "inbound", eventType: "connector.normalized", sourceSchema: `${input.source}.source.v1`, canonicalSchema: "setugov.canonical.v1", payloadSummary: JSON.stringify(normalized), status: "processed" }); await writeAudit(ctx.user.id, ctx.user.role, "connector.exchange", "integration_event", String(input.applicationId), "Independent source record remains with department"); return { normalized }; }),
    updateStep: officialProcedure.input(z.object({ stepId: z.number(), status: z.enum(["in_progress", "completed", "blocked", "rejected"]), remarks: z.string().optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const [step] = await db.select().from(workflowSteps).where(eq(workflowSteps.id, input.stepId)); if (!step) throw new Error("Workflow step not found"); if (ctx.user.role === "official" && ctx.user.departmentId && step.departmentId !== ctx.user.departmentId) throw new TRPCError({ code: "FORBIDDEN", message: "This milestone belongs to another department" }); await db.update(workflowSteps).set({ status: input.status, remarks: input.remarks, startedAt: input.status === "in_progress" ? new Date() : step.startedAt, completedAt: ["completed", "rejected"].includes(input.status) ? new Date() : null }).where(eq(workflowSteps.id, input.stepId)); const allSteps = await db.select().from(workflowSteps).where(eq(workflowSteps.applicationId, step.applicationId)).orderBy(workflowSteps.sequence); const next = allSteps.find(candidate => candidate.sequence > step.sequence && candidate.status === "pending"); if (input.status === "completed" && next) { await db.update(workflowSteps).set({ status: "in_progress", startedAt: new Date() }).where(eq(workflowSteps.id, next.id)); await db.update(applications).set({ status: "in_review", currentDepartmentId: next.departmentId }).where(eq(applications.id, step.applicationId)); await db.insert(integrationEvents).values({ applicationId: step.applicationId, direction: "outbound", eventType: "workflow.routed", sourceSchema: "setugov.workflow.v1", canonicalSchema: "department.task.v1", payloadSummary: `Routed to department ${next.departmentId} without copying source records`, status: "processed" }); } else if (input.status === "rejected") { await db.update(applications).set({ status: "rejected" }).where(eq(applications.id, step.applicationId)); } else if (input.status === "completed") { await db.update(applications).set({ status: "approved", currentDepartmentId: null }).where(eq(applications.id, step.applicationId)); } else { await db.update(applications).set({ status: "action_required" }).where(eq(applications.id, step.applicationId)); } await writeAudit(ctx.user.id, ctx.user.role, `workflow.${input.status}`, "workflow_step", String(input.stepId), input.remarks); return { success: true, nextDepartmentId: next?.departmentId ?? null, finalStatus: input.status === "rejected" ? "rejected" : input.status === "completed" && !next ? "approved" : undefined }; }),
    setConnectorStatus: adminProcedure.input(z.object({ connectorId: z.number(), status: z.enum(["healthy", "degraded", "disabled"]) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(connectors).set({ status: input.status, lastCheckedAt: new Date() }).where(eq(connectors.id, input.connectorId)); await writeAudit(ctx.user.id, ctx.user.role, "connector.status_changed", "connector", String(input.connectorId), input.status); return { success: true }; }),
    updateConnector: adminProcedure.input(z.object({ connectorId: z.number(), name: z.string().min(2), endpoint: z.string().min(3), systemType: z.string().min(2) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(connectors).set({ name: input.name, endpoint: input.endpoint, systemType: input.systemType }).where(eq(connectors.id, input.connectorId)); await writeAudit(ctx.user.id, ctx.user.role, "connector.configured", "connector", String(input.connectorId), `${input.name} · ${input.endpoint}`); return { success: true }; }),
    updateDepartment: adminProcedure.input(z.object({ departmentId: z.number(), name: z.string().min(2), sourceSystem: z.string().min(2) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(departments).set({ name: input.name, sourceSystem: input.sourceSystem }).where(eq(departments.id, input.departmentId)); await writeAudit(ctx.user.id, ctx.user.role, "department.configured", "department", String(input.departmentId), `${input.name} · ${input.sourceSystem}`); return { success: true }; }),
    retryEvent: adminProcedure.input(z.object({ eventId: z.number() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(integrationEvents).set({ status: "processed" }).where(eq(integrationEvents.id, input.eventId)); await writeAudit(ctx.user.id, ctx.user.role, "integration.retry", "integration_event", String(input.eventId)); return { success: true }; }),
    adminOverview: adminProcedure.query(async () => { await seedDemoData(); const db = await getDb(); if (!db) return { departments: [], connectors: [], audits: [], events: [] }; const [depts, conns, audits, events] = await Promise.all([db.select().from(departments), db.select().from(connectors), db.select().from(auditLogs).orderBy(desc(auditLogs.createdAt)).limit(30), db.select().from(integrationEvents).orderBy(desc(integrationEvents.createdAt)).limit(20)]); return { departments: depts, connectors: conns, audits, events }; }),
    normalizePreview: publicProcedure.input(z.object({ source: z.enum(["revenue", "municipal"]), payload: z.record(z.string(), z.string()) })).mutation(({ input }) => input.source === "revenue" ? { name: input.payload.citizen_name, dateOfBirth: input.payload.dob, _mapping: "citizen_name → name · dob → dateOfBirth" } : { name: input.payload.fullName, dateOfBirth: input.payload.date_of_birth?.split("/").reverse().join("-"), _mapping: "fullName → name · date_of_birth → dateOfBirth" }),
  }),
});
export type AppRouter = typeof appRouter;
